version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8

    steps:
      - checkout

      - run: npm install
      - run: npm i -g apollo
      - run: npm run test:setup
      - run: npm test

      # npm start will start a server running at http://localhost:4000/graphql
      # this is the default for apollo-server 2.0
      - run:
          name: Running Server
          command: npm start
          background: true

      # this assumes that ENGINE_API_KEY is set in the environment variables
      - run: apollo schema:check --endpoint=http://localhost:3010/graphql

      # this command will publish the latest version of the schema
      # to Engine but only on the master branch
      - run:
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              apollo schema:publish --endpoint=http://localhost:3010/graphql
            fi
